### ISSUE TITLE
Document globbing syntax

### ISSUE THREAD

**Issue by codekiln** [akesterson/dpath-python#38]
The readme could use some documentation on how globs like `[cd]` work. This doesn't look like regex or even bash globbing, and there aren't too many results on what `eglob` is supposed to refer to outside of references to dpath-python.

**Comment by calebcase** [comment]
Yeah 'eglob' is probably the wrong nomenclature. Not sure where I picked that up other than in [my own code](https://github.com/calebcase/eglob). Bash uses 'extended pattern matching' and refers to the shell option 'extglob':

http://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html

**Comment by calebcase** [comment]
To be even more specific it refers to the feature of '**' as a result of the shell option 'globstar'.

**Comment by akesterson** [comment]
Yeah, the documentation isn't clear on this at all. Sorry about that.

The path globbing syntax is identical to (and is fed directly into) the [fnmatch module](https://docs.python.org/2/library/fnmatch.html). The marker "**" is special and handled by dpath, rather than fnmatch, and it means "at this depth or any further depth in the path tree".

I'll update the docs within a few days for this. The docs are kinda ugly and need restructuring anyway.

**Comment by akesterson** [comment]
Thanks for bringing this up, I've filed a bigger ticket to address our larger documentation issues in #45, this will be resolved with it.
