### ISSUE TITLE
delete_if_exists

### ISSUE THREAD

**Issue by gsemet** [akesterson/dpath-python#87]
`delete` will fail if the node does not exist. Can we have a version (or an arg) that remove if exists ?

**Comment by akesterson** [comment]
Why not just catch the dpath.exceptions.PathNotFound exception and ignore it?

If you don't want to introduce a bad habit like ignoring exceptions, you could search first, then delete. 

Would neither of these be acceptable?

**Comment by gsemet** [comment]
An option just like path.py ‘s mkdir would do the job. Adding try/catch at every calls would be quite overbloated

**Comment by akesterson** [comment]
This is something that certain users in certain circumstances might benefit from, but I don't think it's right for the functionality to belong in dpath.

The least surprising thing for delete() to do if you ask it to delete something that doesn't exist is for it to tell you that you're asking it to perform an action that cannot succeed.

The existence of a mkdir() method in the path.py library seems to potentially support the idea, but the user is advised (in README.rst) to not dig beyond the util library. The stuff in path.py only exists to make the stuff in util.py work, mkdir in particular, because we would reuse that logic in a few different places - but only in the backend. Everything that goes into util.py is a contract with the user, so we don't add code there lightly, as we have to maintain it forever once it's there or until that API spec is deprecated.

Currently our recommendation is to simply catch and discard the exception generated. A  wrapper method will prevent you having to rewrite the same try/except/pass logic over and over again. 

```
def delete_if_exists(obj, path):
    try:
        dpath.util.delete(obj, path)
    except dpath.exceptions.PathNotFound as e:
        pass
```
