### ISSUE TITLE
Feature Request: two ** allowed

### ISSUE THREAD

**Issue by c-bg** [akesterson/dpath-python#88]
Hi. 
Thanks a lot for creating this tool! 
I have an idea for a future feature, let me know what you think on this. 

**Setup:** 
I'm using dpath version 1.4.2 in Python 3.6.8.
**Current Behaviour:** 
```python
import dpath
d = {'1': {'2': {'3': 'c'}}}
dpath.util.search(d, '**/2/**', yielded=True)
```
results in 
`InvalidGlob: Invalid glob. Only one '**' is permitted per glob.`

**Desired Behaviour:**
It would be nice to have support for two **, such that also multiple recurrences of the same key (e.g. if there were two '2' as keys) would be found.
So for the above example the output would be:
 ```python
('1/2', {'3': 'c'})
('1/2/3', 'c')
```
I presume there is a good reason for why this is not available; could you shortly explain the reason? Is there a workaround?
Thanks for your response in advance. 
Have a nice day.

**Comment by calebcase** [comment]
The issue here is that star-star is handled by expanding the single star-star into a series of single stars such that the length of the glob and the path match. If we allow multiple star-star, then this becomes a combinatoric problem where each possible expansion of the star-star has to be produced. While it is possible to do it it would easily produce problems with cpu and memory usage.

For your specific example, it may be sufficient:

```python
import dpath.util

d = {'1': {'2': {'3': 'c'}}}

twos = dpath.util.search(d, '**/2', yielded=True)
for (p, v) in twos:
    print((p, v))
    for (sp, sv) in dpath.util.search(v, '**', yielded=True):
        print(('/'.join([p, sp]), sv))
```
